# Setup
title: âœ…ğŸ´ğŸ”‹[
url: https://correkt.horse
paginate: 1
baseurl: ""
permalink: pretty

# Gems
plugins:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag

# Optimize Jekyll
exclude:
  - .editorconfig
  - .git
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md

sass:
  sass_dir: _sass
  style: :compressed

# Options

# Replace this value and uncomment to enable Google Analytics tracking
ga_analytics: UA-175191928-1

# Specify the author for blog posts
author:
  name: âœ…ğŸ´ğŸ”‹[
  url: https://twitter.com/correkthorse
  email: correkthorse@gmail.com

# Custom vars
version: 3.0.0

# Navbar page list
nav:
  - title: Archive
    url: /archive

  - title: About
    url: /about

site:
  title: âœ…ğŸ´ğŸ”‹[
  twitter_username: correkthorse
  title_image: /assets/profile.png